language: go

go:
  - 1.9

notifications:
  email: false

sudo: true

install:
  - go get github.com/GoASTScanner/gas

script:
  - export GOPATH=$GOPATH:$HOME/gopath/src/github.com/jonases/cybersecuryproject
  - cd src && gas main.go models/* handlers/*
