language: go

go:
  - 1.9

notifications:
  email: false

sudo: true

install:
  - go get github.com/GoASTScanner/gas

script:
  - export GOPATH=$HOME/gopath/src/github.com/jonases/cybersecuryproject:$GOPATH
  - go test
  - cd src && gas ../main.go models/* handlers/* db/* utils/*

