language: go

go:
  - 1.9

notifications:
  email: false

sudo: true


install:
  - go get github.com/GoASTScanner/gas

script:
  - export GOPATH=$GOPATH:$HOME/gopath/src/github.com/jonases/cybersecuryproject
  - gas src/main.go
 


