language: go

go:
  - 1.9

notifications:
  email: false

sudo: true

env:
  - GOPATH=$GOPATH:$HOME/gopath/src/github.com/jonases/cybersecuryproject

install:
  - go get github.com/GoASTScanner/gas

script:
  - gas src/main.go
 


