language: go

go:
  - 1.9

install:
  - go get github.com/GoASTScanner/gas
  - go get github.com/IBM-Bluemix/go-cloudant
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/sessions
  - go get github.com/josephspurrier/csrfbanana
  - go get github.com/timjacobi/go-couchdb
  - go get golang.org/x/crypto/bcrypt
  

script:
  - export GOPATH=$HOME/gopath/src/github.com/jonases/cybersecuryproject:$GOPATH
  - go test -v
  #- cd src && gas ../main.go models/* handlers/* db/* utils/*
  - gas main.go models/* handlers/* db/* utils/*

